Section description
smerch88/Psychology_Website pull request #4
Opened 2022-10-21 11:03 UTC by Romagek

2022-10-21 11:22 UTC, smerch88 requested changes

2022-10-21 11:22 UTC, smerch88 commented on src/partials/description.html
> +    <div class="container__aboutme">
aboutme - 2 слова, напиши их через - about-me  или выбери просто 1 слово, например  container__about

2022-10-21 11:22 UTC, smerch88 commented on src/partials/description.html
> +        <span class="description__abouttext">
abouttext 2 слова, напиши одним

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    z-index: 0;
если индекс 0, то его не надо указывать, он такой по дефолту

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    padding-bottom: 28px;
внутри контейнера старяйся использовать марджины, а не паддинги

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    color: #506054;
миксин

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    font-style: normal;
по идее он дефолтно нормал

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    font-family: 'Raleway';
миксин

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    font-style: normal;
дефолтный стиль?

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    font-weight: 400;
дефолтный вес?

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    line-height: 27px;
прописать относительный параметр

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    color: #506054;
миксин

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    text-transform: uppercase;
нужен ли трансформ?

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    line-height: 150%;
что бы в 1 стиле код был, напиши не 150%, а 1.5

2022-10-21 11:22 UTC, smerch88 commented on src/sass/components/_description.scss
> +    line-height: 150%;
1.5

2022-10-25 10:56 UTC, Romagek commented on src/partials/description.html
> +    <div class="container__aboutme">
+

2022-10-25 10:57 UTC, Romagek commented on src/sass/components/_description.scss
> +    text-transform: uppercase;
+

2022-10-25 10:59 UTC, Romagek commented on src/sass/components/_description.scss
> +    line-height: 150%;
+

2022-10-25 10:59 UTC, Romagek commented on src/sass/components/_description.scss
> +    line-height: 150%;
+

2022-10-25 11:06 UTC, Romagek commented on src/partials/description.html
> +      <h3 class="description__glawtext--start">Вітаю! Мене звати Анна</h3>
+

2022-10-25 11:07 UTC, Romagek commented on src/partials/description.html
> +      <h2 class="description__glawtext--end">Я - практикуючий психолог.</h2>
+

2022-10-25 11:21 UTC, Romagek commented on src/sass/components/_description.scss
> +    font-family: 'Cormorant Garamond';
+

2022-10-25 11:24 UTC, Romagek commented on src/sass/components/_description.scss
> +    line-height: 27px;
+

2022-10-25 11:26 UTC, Romagek commented on src/sass/components/_description.scss
> +    color: #506054;
+

2022-10-25 11:26 UTC, Romagek commented on src/sass/components/_description.scss
> +    line-height: 30px;
+

2022-10-27 15:20 UTC, merged